
import { Tool, ToolCategory } from './types';

export const CONVERSION_TOOLS: Tool[] = [
  // AI Tools
  {
    id: 'ai-jpg-to-text',
    name: 'JPG to Text (OCR)',
    description: 'Extract text from any JPG image using powerful AI.',
    category: ToolCategory.AI,
    fromFormat: 'JPG',
    toFormat: 'TXT',
    accept: 'image/jpeg',
    isAiPowered: true,
  },
  {
    id: 'ai-png-to-text',
    name: 'PNG to Text (OCR)',
    description: 'Extract text from any PNG image using powerful AI.',
    category: ToolCategory.AI,
    fromFormat: 'PNG',
    toFormat: 'TXT',
    accept: 'image/png',
    isAiPowered: true,
  },
  // PDF Tools
  {
    id: 'pdf-to-docx',
    name: 'PDF to DOCX',
    description: 'Convert your PDF files to editable Word documents.',
    category: ToolCategory.PDF,
    fromFormat: 'PDF',
    toFormat: 'DOCX',
    accept: 'application/pdf',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each page of your PDF into a high-quality JPG image.',
    category: ToolCategory.PDF,
    fromFormat: 'PDF',
    toFormat: 'JPG',
    accept: 'application/pdf',
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into a single document.',
    category: ToolCategory.PDF,
    fromFormat: 'PDF',
    toFormat: 'PDF',
    accept: 'application/pdf',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract one or more pages from your PDF file.',
    category: ToolCategory.PDF,
    fromFormat: 'PDF',
    toFormat: 'PDF',
    accept: 'application/pdf',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce the file size of your PDF while optimizing for quality.',
    category: ToolCategory.PDF,
    fromFormat: 'PDF',
    toFormat: 'PDF',
    accept: 'application/pdf',
  },
  // Document Tools
  {
    id: 'docx-to-pdf',
    name: 'DOCX to PDF',
    description: 'Convert Word documents to professional-looking PDF files.',
    category: ToolCategory.DOCUMENT,
    fromFormat: 'DOCX',
    toFormat: 'PDF',
    accept: '.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  },
  {
    id: 'xlsx-to-pdf',
    name: 'XLSX to PDF',
    description: 'Convert Excel spreadsheets to PDF for easy sharing.',
    category: ToolCategory.DOCUMENT,
    fromFormat: 'XLSX',
    toFormat: 'PDF',
    accept: '.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  },
  {
    id: 'pptx-to-pdf',
    name: 'PPTX to PDF',
    description: 'Convert PowerPoint presentations to PDF format.',
    category: ToolCategory.DOCUMENT,
    fromFormat: 'PPTX',
    toFormat: 'PDF',
    accept: '.pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation',
  },
  // Image Tools
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    description: 'Convert JPG images to PNG format with transparency support.',
    category: ToolCategory.IMAGE,
    fromFormat: 'JPG',
    toFormat: 'PNG',
    accept: 'image/jpeg',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    description: 'Convert PNG images to JPG format for smaller file sizes.',
    category: ToolCategory.IMAGE,
    fromFormat: 'PNG',
    toFormat: 'JPG',
    accept: 'image/png',
  },
  {
    id: 'webp-to-jpg',
    name: 'WEBP to JPG',
    description: 'Convert modern WEBP images to the universally compatible JPG format.',
    category: ToolCategory.IMAGE,
    fromFormat: 'WEBP',
    toFormat: 'JPG',
    accept: 'image/webp',
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG',
    description: 'Convert Apple\'s HEIC photos to standard JPG format.',
    category: ToolCategory.IMAGE,
    fromFormat: 'HEIC',
    toFormat: 'JPG',
    accept: 'image/heic',
  },
  // Archive Tools
  {
    id: 'zip-extractor',
    name: 'Zip Extractor',
    description: 'Uncompress ZIP files online to access their contents.',
    category: ToolCategory.ARCHIVE,
    fromFormat: 'ZIP',
    toFormat: 'Files',
    accept: '.zip,application/zip',
  },
];
